import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./_components/Header/Header";

import { GoogleTagManager } from '@next/third-parties/google'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
      <GoogleTagManager gtmId="GTM-M4K5Z3BP" />
        <body>
          <TRPCReactProvider>
          <Header />
          {children}
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
